services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: schedulerdb
      POSTGRES_USER: scheduleruser
      POSTGRES_PASSWORD: schedulerpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "scheduleruser", "-d", "schedulerdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: sh -c "cd job_schedular && python3 manage.py migrate && gunicorn config.wsgi:application --worker-class gevent --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build: .
    command: sh -c "cd job_schedular && celery -A config worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data: